### PR TITLE
Fixed Transforms

### LINKED ISSUE #5: CTransform.Combine needs fixing and testing
https://github.com/crashcloud/crash.changes/blob/b8501a3dae8b7def46841dbe0c1ce94c722cfba5/src/Geometry/CTransform.cs#L118-L132

### PR DESCRIPTION
**Pull request by Lukasfuh**
I fixed the transforms by calcualting the dot product instead of adding things up.

### CODE REVIEW

File: src/Geometry/CTransform.cs [hunk 1]
```diff
@@ -76,17 +76,52 @@ private static double[][] GetUniformMatrix(double value)
...
 
 		/// <summary>Tests the Matrix for any NaN's or infinity numbers</summary>
 		public bool IsValid()
 		{
-			double[] values = _transforms.SelectMany(t => t).ToArray();
+			double[] values = Flatten(_transforms);
+
+			// Check that the matrix is all zeros
+			if (values.All(v => v == 0))
+				return true;
```
Comment (clicky) [inline src/Geometry/CTransform.cs]: Should this be valid? If so I need to update my check in Crash!
And if it is valid, is there a way to check for "IsDefault" or something? This transform in Rhino turns things inside out somehow and it'd be great if I can discard 0 transforms :)

File: src/Geometry/CTransform.cs [hunk 2]
```diff
@@ -5,15 +5,15 @@
 	public struct CTransform : IEnumerable<double>
```
Comment (clicky) [inline src/Geometry/CTransform.cs:5]: I also wonder if we should turn the CGeometries into `Readonly` Structs. What do you recon Lukas?

File: src/Geometry/CTransform.cs [hunk 3]
```diff
@@ -5,15 +5,15 @@
...
 	{
 		/// <summary>the transform matrix</summary>
-		private readonly double[][] _transforms;
+		private readonly double[,] _transforms;
```
Comment (clicky) [inline src/Geometry/CTransform.cs:8]: Ooooh, I did not know you could do this, this is WAY better

File: src/Geometry/CTransform.cs [hunk 4]
```diff
@@ -76,17 +76,52 @@ private static double[][] GetUniformMatrix(double value)
 			return matrix;
 		}
 
+		/// <summary>Returns a Identity Matrix</summary>
+		private static double[,] GetIdentityMatrix()
```
Comment (clicky) [inline src/Geometry/CTransform.cs:85]: Could you explain a bit more about what one of these is? I assume its a transform/matrix that does nothing?

File: src/Geometry/CTransform.cs (hunk 1 above)
Comment (clicky) [reply src/Geometry/CTransform.cs]: Maybe `IsIdentity?` Just saw the method above

Comment (Lukasfuh) [reply src/Geometry/CTransform.cs]: everything 0 should actually not be valid. The identity matrix means nothing happens. The 0 matrix is not valid because if we add any transformation to it the product of it will also result to 0. Its kind of multiplying all the transformations with 0 which results to nothing

File: src/Geometry/CTransform.cs (hunk 4 above)
Comment (Lukasfuh) [reply src/Geometry/CTransform.cs:85]: An identity matrix has a 1 along the diagonal. It basically means there is no transformation but its a valid matrix. A zero matrix would not be valid because any transformation added to it will result to nothing. I explained it briefly above
